# Generated by Django 5.0 on 2024-12-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(default='INITIATED', max_length=20)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('auth', models.CharField(blank=True, max_length=50, null=True)),
                ('ref', models.CharField(blank=True, max_length=50, null=True)),
                ('tran_id', models.CharField(blank=True, max_length=50, null=True)),
                ('encrypted_response', models.TextField(blank=True, null=True)),
                ('decrypted_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
