# Generated by Django 3.2 on 2025-01-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knet', '0002_paymenttransaction_delete_knettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='error_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
