# Generated by Django 3.2 on 2025-03-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knet', '0003_paymenttransaction_error_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={},
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='error_code',
            new_name='auth_code',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='error_text',
            new_name='decrypted_response',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='reference_id',
            new_name='post_date',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='transaction_id',
            new_name='tran_id',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='error_details',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='response_data',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='encrypted_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='udf1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='udf2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='udf3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='udf4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='udf5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
